const result=[
    {
    "No":"11",
    "date":"4th December 2021, 19:00 PM",
    "team1":"Spain",
    "team2":"England",
    "img1":"flag/Spain.png",
    "img2":"flag/download.png",
    "team1_prob":"45%",
    "team2_prob":"55%",
    "matches":"15",
    "team1_win":"7",
    'team2_win':"5",
    "draw":"3",
    "team1_top":"David Villa",
    "team2_top":"David Beckham",
    "team1_history":[1,0,1,0,0],
    "team2_history":[0,1,0,1,1],
    "team1_recent":[1,0,1,0,-1],
    "team2_recent":[0,1,0,1,1],

    "team1_player":"Álvaro Morata",
    "team2_player":"Jack Grealish"
},


{
    "No":"12",
    "date":"6th December 2021, 19:00 PM",
    "team1":"Germany",
    "team2":"Brazil",
    "img1":"flag/Germany.png",
    "img2":"flag/Brazil.png",
    "team1_prob":"50%",
    "team2_prob":"50%",
    "matches":"12",
    "team1_win":"5",
    'team2_win':"4",
    "draw":"3",
    "team1_top":"Miroslav Klose",
    "team2_top":"Ronaldinho",
    "team1_history":[1,0,1,0,-1],
    "team2_history":[0,1,0,1,-1],
    "team1_recent":[1,0,1,0,0],
    "team2_recent":[0,1,0,1,1],

    "team1_player":"Kai Havertz",
    "team2_player":"Neymar"
},
{
    "No":"13",
    "date":"7th December 2021, 19:00 PM",
    "team1":"Chile",
    "team2":"France",
    "img1":"flag/Chile.png",
    "img2":"flag/France.png",
    "team1_prob":"20%",
    "team2_prob":"70%",
    "matches":"8",
    "team1_win":"2",
    'team2_win':"5",
    "draw":"1",
    "team1_top":"Alexis Sánchez",
    "team2_top":"Zinedine Zidane",
    "team1_history":[0,0,1,0,-1],
    "team2_history":[1,1,0,1,-1],
    "team1_recent":[1,0,0,0,0],
    "team2_recent":[1,1,-1,1,1],

    "team1_player":"Ben Brereton",
    "team2_player":"Paul Pogba"
},

{
    "No":"14",
    "date":"8th December 2021, 19:00 PM",
    "team1":"Argentina",
    "team2":"England",
    "img1":"flag/Argentina.jpg",
    "img2":"flag/download.png",
    "team1_prob":"50%",
    "team2_prob":"50%",
    "matches":"20",
    "team1_win":"9",
    'team2_win':"9",
    "draw":"2",
    "team1_top":"Lionel Messi",
    "team2_top":"Wayne Rooney",
    "team1_history":[0,0,1,0,-1],
    "team2_history":[1,1,0,1,-1],
    "team1_recent":[1,0,1,0,1],
    "team2_recent":[1,1,-1,0,1],

    "team1_player":"Lionel Messi",
    "team2_player":"Harry Kane"
},

{
    "No":"15",
    "date":"9th December 2021, 19:00 PM",
    "team1":"Spain",
    "team2":"Netherland",
    "img1":"flag/Spain.png",
    "img2":"flag/Netharland.png",
    "team1_prob":"60%",
    "team2_prob":"40%",
    "matches":"17",
    "team1_win":"9",
    'team2_win':"8",
    "draw":"0",
    "team1_top":"Fernando Torres",
    "team2_top":"Faas Wilkes",
    "team1_history":[1,0,1,0,1],
    "team2_history":[0,1,0,1,0],
    "team1_recent":[1,0,1,0,1],
    "team2_recent":[1,1,-1,0,1],

    "team1_player":"Sergio Ramos",
    "team2_player":"Memphis Depay"
},
{
    "No":"16",
    "date":"10th December 2021, 19:00 PM",
    "team1":"Uruguay",
    "team2":"Norway",
    "img1":"flag/Uruguay.png",
    "img2":"flag/Norway.png",
    "team1_prob":"60%",
    "team2_prob":"40%",
    "matches":"7",
    "team1_win":"5",
    'team2_win':"1",
    "draw":"1",
    "team1_top":"Diego Forlán    ",
    "team2_top":"John Arne Riise    ",
    "team1_history":[0,0,0,0,0],
    "team2_history":[1,1,1,1,1],
    "team1_recent":[1,0,1,0,1],
    "team2_recent":[1,1,-1,0,1],

    "team1_player":"Luis Suárez ",
    "team2_player":"Martin Ødegaard"
},
{
    "No":"17",
    "date":"11th December 2021, 19:00 PM",
    "team1":"Italy",
    "team2":"France",
    "img1":"flag/Italy.png",
    "img2":"flag/France.png",
    "team1_prob":"51%",
    "team2_prob":"49%",
    "matches":"21",
    "team1_win":"10",
    'team2_win':"9",
    "draw":"2",
    "team1_top":"Alessandro Del Piero ",
    "team2_top":"Laurent Blanc ",
    "team1_history":[1,1,0,-1,-1],
    "team2_history":[0,0,1,-1,-1],
    "team1_recent":[1,1,1,1,1],
    "team2_recent":[1,1,-1,1,1],

    "team1_player":"Federico Chiesa",
    "team2_player":" Karim Benzema"
},

{
    "No":"18",
    "date":"12th December 2021, 19:00 PM",
    "team1":"Spain",
    "team2":"Brazil",
    "img1":"flag/Spain.png",
    "img2":"flag/Brazil.png",
    "team1_prob":"55%",
    "team2_prob":"45%",
    "matches":"16",
    "team1_win":"8",
    'team2_win':"6",
    "draw":"2",
    "team1_top":"Xavi ",
    "team2_top":"Kaka ",
    "team1_history":[1,1,0,-1,-1],
    "team2_history":[0,0,1,-1,-1],
    "team1_recent":[1,1,1,1,1],
    "team2_recent":[1,1,0,1,1],

    "team1_player":"Sergio Ramos    ",
    "team2_player":"Marcelo Vieira"
},
{
    "No":"19",
    "date":"13th December 2021, 19:00 PM",
    "team1":"Chile",
    "team2":"Argentina",
    "img1":"flag/Chile.png",
    "img2":"flag/Argentina.png",
    "team1_prob":"41%",
    "team2_prob":"59%",
    "matches":"16",
    "team1_win":"10",
    'team2_win':"6",
    "draw":"0",
    "team1_top":"Leonel Sanchez  ",
    "team2_top":"Lionel Messi",
    "team1_history":[1,1,0,-1,-1],
    "team2_history":[0,0,1,-1,-1],
    "team1_recent":[1,1,0,0,1],
    "team2_recent":[1,1,0,1,1],

    "team1_player":"Arturo Vidal    ",
    "team2_player":"Paulo Dybala"
},

{
    "No":"20",
    "date":"14th December 2021, 19:00 PM",
    "team1":"Italy",
    "team2":"Norway",
    "img1":"flag/Italy.png",
    "img2":"flag/Norway.png",
    "team1_prob":"80%",
    "team2_prob":"20%",
    "matches":"6",
    "team1_win":"6",
    'team2_win':"0",
    "draw":"0",
    "team1_top":" Alessandro Del Piero",
    "team2_top":"Alexander Sørloth",
    "team1_history":[1,1,1,1,1],
    "team2_history":[0,0,0,0,0],
    "team1_recent":[1,1,1,1,1],
    "team2_recent":[1,1,0,1,0],

    "team1_player":"Ciro Immobile    ",
    "team2_player":"Erling Haaland"
},


{
    "No":"21",
    "date":"15th December 2021, 19:00 PM",
    "team1":"Brazil",
    "team2":"Netherland",
    "img1":"flag/Brazil.png",
    "img2":"flag/Netherland.png",
    "team1_prob":"60%",
    "team2_prob":"40%",
    "matches":"9",
    "team1_win":"6",
    'team2_win':"3",
    "draw":"0",
    "team1_top":" Kaka",
    "team2_top":"Robin van Persie    ",
    "team1_history":[1,1,0,1,0],
    "team2_history":[0,0,1,0,1],
    "team1_recent":[1,1,0,-1,0],
    "team2_recent":[1,1,0,1,1],

    "team1_player":"Neymar    ",
    "team2_player":"Virgil van Dijk    "
},
{
    "No":"22",
    "date":"16th December 2021, 19:00 PM",
    "team1":"Uruguay",
    "team2":"England",
    "img1":"flag/Uruguay.png",
    "img2":"flag/download.png",
    "team1_prob":"55%",
    "team2_prob":"45%",
    "matches":"9",
    "team1_win":"4",
    'team2_win':"4",
    "draw":"1",
    "team1_top":" Frank Lampard    ",
    "team2_top":"Edinson Cavani    ",
    "team1_history":[1,1,0,1,0],
    "team2_history":[0,0,1,0,1],
    "team1_recent":[1,1,0,-1,0],
    "team2_recent":[1,1,0,1,1],

    "team1_player":"Harry Kane",
    "team2_player":" Edinson Cavani  "
},


{
    "No":"23",
    "date":"17th December 2021, 19:00 PM",
    "team1":"Germany",
    "team2":"Italy",
    "img1":"flag/Germany.png",
    "img2":"flag/Italy.png",
    "team1_prob":"49%",
    "team2_prob":"51%",
    "matches":"22",
    "team1_win":"11",
    'team2_win':"10",
    "draw":"1",
    "team1_top":" Miroslav Klose    ",
    "team2_top":"Fabio Cannavaro    ",
    "team1_history":[1,1,0,-1,0],
    "team2_history":[0,0,1,-1,1],
    "team1_recent":[1,1,0,-1,0],
    "team2_recent":[1,1,0,1,1],

    "team1_player":"Thomas Müller    ",
    "team2_player":" Gianluigi Donnarumma  "
},

{
    "No":"24",
    "date":"18th December 2021, 19:00 PM",
    "team1":"Spain",
    "team2":"Argentina",
    "img1":"flag/Spain.png",
    "img2":"flag/Argentina.png",
    "team1_prob":"50%",
    "team2_prob":"50%",
    "matches":"10",
    "team1_win":"6",
    'team2_win':"4",
    "draw":"0",
    "team1_top":" Diego Costa    ",
    "team2_top":"Sergio Agüero   ",
    "team1_history":[1,1,0,-1,-1],
    "team2_history":[0,0,1,-1,-1],
    "team1_recent":[1,1,0,-1,0],
    "team2_recent":[1,1,0,1,1],

    "team1_player":"Gerard Moreno    ",
    "team2_player":" Lionel Messi  "
},

{
    "No":"25",
    "date":"19th December 2021, 19:00 PM",
    "team1":"Chile",
    "team2":"France",
    "img1":"flag/Chile.png",
    "img2":"flag/France.png",
    "team1_prob":"20%",
    "team2_prob":"80%",
    "matches":"10",
    "team1_win":"2",
    'team2_win':"7",
    "draw":"1",
    "team1_top":" Alexis Sánchez   ",
    "team2_top":"Zinedine Zidane ",
    "team1_history":[0,0,0,-1,1],
    "team2_history":[1,1,1,-1,0],
    "team1_recent":[1,1,0,-1,1],
    "team2_recent":[1,1,0,1,1],

    "team1_player":" Alexis Sánchez ",
    "team2_player":" Kylian Mbappé    "
},

{
    "No":"26",
    "date":"20th December 2021, 19:00 PM",
    "team1":"Norway",
    "team2":"Uruguay",
    "img1":"flag/Norway.png",
    "img2":"flag/Uruguay.png",
    "team1_prob":"35%",
    "team2_prob":"65%",
    "matches":"10",
    "team1_win":"2",
    'team2_win':"5",
    "draw":"3",
    "team1_top":" Jens Petter Hauge    ",
    "team2_top":"Luis Suárez    ",
    "team1_history":[0,0,1,-1,1],
    "team2_history":[1,1,0,-1,0],
    "team1_recent":[1,1,0,-1,1],
    "team2_recent":[1,1,0,1,1],

    "team1_player":" Jens Petter Hauge ",
    "team2_player":" Giorgian de Arrascaeta    "
},

{
    "No":"27",
    "date":"21st December 2021, 19:00 PM",
    "team1":"England",
    "team2":"Argentina",
    "img1":"flag/download.png",
    "img2":"flag/Argentina.png",
    "team1_prob":"49%",
    "team2_prob":"51%",
    "matches":"18",
    "team1_win":"8",
    'team2_win':"10",
    "draw":"3",
    "team1_top":" David Beckham  ",
    "team2_top":"Lionel Messi   ",
    "team1_history":[0,0,1,-1,1],
    "team2_history":[1,1,0,-1,0],
    "team1_recent":[1,1,0,-1,1],
    "team2_recent":[1,1,0,1,1],

    "team1_player":" Harry Kane ",
    "team2_player":" Lionel Messi  "
},

{
    "No":"28",
    "date":"22nd December 2021, 19:00 PM",
    "team1":"Italy",
    "team2":"France",
    "img1":"flag/Italy.png",
    "img2":"flag/France.png",
    "team1_prob":"52%",
    "team2_prob":"48%",
    "matches":"25",
    "team1_win":"13",
    'team2_win':"10",
    "draw":"2",
    "team1_top":" Lorenzo Insigne    ",
    "team2_top":"Zinedine Zidane    ",
    "team1_history":[1,0,1,-1,1],
    "team2_history":[0,1,0,-1,0],
    "team1_recent":[1,1,0,-1,1],
    "team2_recent":[1,1,0,1,1],

    "team1_player":" Marco Verratti    ",
    "team2_player":" Antoine Griezmann    "
},
]


    


